### PR TITLE
Fix macOS buid fail

### PR DESCRIPTION
**Pull request by ChrisJones687**

### CODE REVIEW

**Comment by ChrisJones687** [comment]
@wenzeslaus adding the override here passes the R build process for all 3 OS put fails here on CMake. Thoughts.

**Review by wenzeslaus — APPROVED** [review]
As far as I understand, this was only a compilation warning in https://github.com/ncsu-landscape-dynamics/rpops/pull/39 not an error, but that's actually just depends on the choice of compiler flags. (Looks like compiler warning is a failure for the check.)

Anyway, we _do_ want the override to be there.

We need to add clang to CI here (#113) so that we get all the checks which both GCC and Clang enable with -Wall -Wextra which are apparently different in each case.

**Comment by ChrisJones687** [comment]
Yes, it is a compilation warning. And a compilation warning of any kind translates to a build error in R and inability to install the package. Warnings as failures were the main reason for adding the GitHub actions so we could test builds on all 3 OS in ncsu-landscape-dynamics/rpops#39.

**Comment by ChrisJones687** [comment]
Fixes #111

**Comment by wenzeslaus** [comment]
Thanks for the clarification.

**Pull request merged**
