### PR TITLE
Spatial index

### PR DESCRIPTION
**Pull request by ChrisJones687**
I ended up using std::vector as std::pair is a specific case of std::tuple and doesn't work as well with R.

### CODE REVIEW

**Comment by ChrisJones687** [comment]
Finished profiling. A couple of notes. I ran the profiling on my laptop as I thought it would be more representative of server cpu speed than my desktop. Results are plotted below for 10 runs at each host level. Interestingly, on a percentage basis it gets better at higher levels of host availability and smooths out variability in run times. Not 100% sure why other than it completely eliminates the calculations in dispersers where there are no hosts rather than checking if it is there at all.


profile_comparison

**Review by malawrim — APPROVED** [review]
Looks good to me

**Review by wenzeslaus — CHANGES_REQUESTED** [review]
For the naming try:

```cpp
        for (auto indices : suitable_cells) {
            int i = indices[0];
            int j = indices[1];
            auto value = quarantine_areas(i, j);
```

**Review by wenzeslaus — APPROVED** [review]

**Comment by ChrisJones687** [comment]
closes # 116

**Pull request merged**
